### ISSUE TITLE
Unable to rename channels

### ISSUE THREAD

**Issue by Frerduro** [DynamicaBot/Dynamica#188]
### Version

The version of the bot is 2022.11.6. The discord.js version is 14.6.0.

### Hosting method

Docker

### Bug description

/name says it failes but there are no errors in console output.

![image](https://user-images.githubusercontent.com/35627247/219904089-45802732-9355-4518-977e-0a14c0e4286c.png)

### Steps to reproduce

do /name

### Relevant log output

```shell
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from dynamicabot/dynamica 
Status: Image is up to date for ghcr.io/dynamicabot/dynamica:2022-pterodactyl 
Digest: sha256:7b5503ad0f69877919cf522241783cf1042ea3d790a0cd4d69a69831fd1765cc 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/app$ yarn deploy; npx prisma migrate deploy;yarn start
yarn run v1.22.19
$ echo "This script is no longer used. All you need to do is run yarn start and deployment happens automatically."
This script is no longer used. All you need to do is run yarn start and deployment happens automatically.
Done in 0.05s.
Prisma schema loaded from schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:/home/container/dynamica/db.sqlite"
14 migrations found in prisma/migrations
No pending migrations to apply.
yarn run v1.22.19
$ node --enable-source-maps .
[2023-02-18] [18:29:11] [Deploy] › ▶  deploy    Initialized timer...
[2023-02-18] [18:29:12] [Deploy] › ◼  deploy    Timer run for: 244ms
[2023-02-18] [18:29:12] [Event::Ready] › ℹ  info      Ready! Logged in as AVN Voice Bot#3088
container@pterodactyl~ Server marked as running...
[2023-02-18] [18:29:12] [Event::Ready] › ℹ  info      Loaded 2 primaries
[2023-02-18] [18:29:12] [Event::Ready] › ℹ  info      Loaded 1 secondaries
[2023-02-18] [18:29:28] › ℹ  info      1076644427281477652 name changed.
```

**Comment by Frerduro** [comment]
```
✘  error     Unhandled Rejection DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:497:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.queueRequest (/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:198:11)
    at REST.request (/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at async ChatInputCommandInteraction.reply (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1076646667102724246/aW50ZXJhY3Rpb246MTA3NjY0NjY2NzEwMjcyNDI0NjphWkFwTlhPOTQ1czFNTnRUSVp1SllXN25YUEZEVG5BeE1WRHVmTDNlSEZTR1ZHcmUydmFLa1N2ZlVHeXVsaDhKbWVxeXo4eEpVWjYwSFJGeG9LeFZyUWdZdVA4NG83b0FTcmFFNXdyaGRFWjZpRElYUE9VSk9TZURTSEs2M1dKeQ/callback'
}
```

Got this error multiple minutes after I submitted the bug report

**Comment by sebasptsch** [comment]
Hmm. Ok, I'll take a look today

**Comment by sebasptsch** [comment]
I've updated the docker image, you might need to edit the config for pterodactyl to use `ghcr.io/DyanmicaBot/Dynamica:2022-latest` to `ghcr.io/dynamicabot/dynamica:latest-pterodactyl`

**Comment by Frerduro** [comment]
looks like its working again without having to switch the config.
